name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Hello and welcome to our open-source community!\nThank you for opening your first issue. We're excited to have you here. Please provide as many details as possible, and our team will get back to you shortly to assist with your request. Feel free to explore our existing issues and projects to find other ways to get involved.\nHappy contributing! 🚀' first issue"
        pr-message: "🎉 Congratulations on your first pull request!\nWe appreciate your contribution to our project. Please make sure your pull request (PR) follows our contribution guidelines and includes a clear description of the changes you've made. If you need help or have any questions, don't hesitate to ask – we're here to assist you.\nThank you for being a part of our community! 🙌' first pull request"
